language: objective-c
before_install:
  - brew update
  - brew uninstall xctool
  - brew install xctool
  - export LANG=en_US.UTF-8
  - gem i cocoapods --no-ri --no-rdoc
  - pod install
xcode_workspace: ARASCIISwizzle.xcworkspace
xcode_scheme:
  - Demo
  - Tests
xcode_sdk: iphonesimulator

