language: objective-c
before_script:
  - brew update
  - brew uninstall xctool
  - brew install xctool
  - export LANG=en_US.UTF-8
  - cd Demo ; pod install ; cd ..
xcode_workspace: Demo/Demo.xcworkspace
xcode_scheme: Demo
xcode_sdk: iphonesimulator

