pod "ARASCIISwizzle", :path => "../ARASCIISwizzle.podspec"
pod "FLKAutoLayout", "~> 0.1.1"
pod "ORStackView", "~> 1.0.0"

target "DemoTests" do
  pod 'Specta', '~> 0.2.1'
  pod 'Expecta', '~> 0.2.3'
  pod 'FBSnapshotTestCase', :head
  pod 'EXPMatchers+FBSnapshotTest', :head
end

